### ISSUE TITLE
Vite v4.x Support?

### ISSUE THREAD

**Issue by jaswrks** [voracious/vite-plugin-node-polyfills#10]
>  Found: vite@4.0.3
>  npm ERR! node_modules/vite
>  npm ERR!   vite@"^4.0.3" from the root project
>  npm ERR! 
>  npm ERR! Could not resolve dependency:
>  npm ERR! peer vite@"^2.0.0 || ^3.0.0" from vite-plugin-node-polyfills@0.5.0

Would it be possible to support Vite v4.x in this plugin, please?

**Comment by voracious** [comment]
Thanks for bringing this to my attention!

I just need to loosen the peer dependency requirements and test it out. I'll get a fix for that out ASAP.

**Comment by voracious** [comment]
This has been fixed in `v0.6.0`.

**Comment by jaswrks** [comment]
Thank you SO much. Happy Holidays 🎄
