### ISSUE TITLE
Vite 4.0.4 and latest polyfills

### ISSUE THREAD

**Issue by Manubi** [voracious/vite-plugin-node-polyfills#12]
Hi,
I get the following error when I try this plugin with vite.

```✘ [ERROR] The injected path "/Users/mbichler/dev/resolute/frontend_react/node_modules/node-stdlib-browser/helpers/esbuild/shim.js" cannot be marked as external```

![CleanShot 2023-01-09 at 11 54 29](https://user-images.githubusercontent.com/20935138/211292144-a6abb1d1-bc47-4739-9e9c-f664a376638d.png)

**Comment by voracious** [comment]
Hey there, @Manubi! There is an open issue for this already, so I'm going to close this one. Feel free to follow along at #11.

**Comment by xpluscal** [comment]
You're a lifesaver @voracious
