### ISSUE TITLE
remove 74 MByte yarn packages from git

### ISSUE THREAD

**Issue by milahu** [voracious/vite-plugin-node-polyfills#2]
```sh
du -sh .yarn
# 74M     .yarn

du -sh .git
# 41M     .git

git filter-repo  --invert-paths \
--path .yarn/ --path .pnp.cjs --path .pnp.loader.mjs --path .yarnrc.yml

du -sh .git
# 224K    .git
```

done in my fork
https://github.com/milahu/vite-plugin-node-polyfills

**Comment by voracious** [comment]
Hi @milahu. These files are not included on install. They are only included in source control to make local development of this package faster.

**Comment by milahu** [comment]
> make local development of this package faster

no, fetching packages from github is as slow as fetching packages from npm

but maybe everybody else is doing it wrong : D

**Comment by voracious** [comment]
@milahu this is [the recommended approach for Yarn 2+ with zero installs](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored). I do see that I accidentally included the `.yarn/unplugged` dir though, so removing that should reduce the size a bit.
