### ISSUE TITLE
remove typescript

### ISSUE THREAD

**Issue by milahu** [voracious/vite-plugin-node-polyfills#3]
typescript is overkill

see

https://github.com/milahu/vite-plugin-node-polyfills/commit/6174c9ba4209839dee0483433babc855744c9b24

https://github.com/milahu/vite-plugin-node-polyfills/commit/48ddf9224c01f1cd5517cb58ff71e3bb2f3567ab

https://github.com/milahu/vite-plugin-node-polyfills/commit/d77ff383537f53a22e857f57a73c90fd31ae89c0

https://github.com/milahu/vite-plugin-node-polyfills/commit/d41b9d9a946c98b1b9959a79e084c572985fe8a9

**Comment by voracious** [comment]
I appreciate the thought, but I personally prefer TypeScript for local development. You do not need to use it in your projects to use this package.
