### ISSUE TITLE
rollup-plugin-inject is deprecated, rollup-plugin-node-polyfills is unmaintained

### ISSUE THREAD

**Issue by milahu** [voracious/vite-plugin-node-polyfills#6]
https://github.com/ionic-team/rollup-plugin-node-polyfills/pull/32

> the repo seems to be dead

https://github.com/remorses/esbuild-plugins/issues/18

> `@FredKSchott`'s fork is also recommended by the `@rollup` team: https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency

https://github.com/cloudflare/wrangler2/issues/1232

> Perhaps we could switch to https://github.com/niksy/node-stdlib-browser instead of @esbuild-plugins/node-modules-polyfill?

alternative:
https://github.com/sodatea/vite-plugin-node-stdlib-browser
... "just works" : )

**Comment by voracious** [comment]
I appreciate the info. I'm definitely liking the looks of [niksy/node-stdlib-browser](https://github.com/niksy/node-stdlib-browser), so I'll likely switch to using that internally. That said, the other open issues surface problems other than old dependencies, so I'm going to close this one in favor of those.
