### ISSUE TITLE
Cannot rollup in NuxtJS 3

### ISSUE THREAD

**Issue by gaminglifex** [voracious/vite-plugin-node-polyfills#7]
I am trying put third-party markdown editor into my project, and it is lucky to have this plugin to solve the problem:
`"Module "stream" has been externalized for browser compatibility. Cannot access "stream.Readable" in client code."`

However, when I am trying to build my project for production, there is an error occur:
![image](https://user-images.githubusercontent.com/72642816/196342275-32be17cd-adfb-4df3-ab12-4acd6a39a7ed.png)

I am able to build my project without adding this plugin to vite config, but all my markdown components & Github Octokit modules will not be functional.

Therefore, I would like to know if there is any solution regarding to my problem?

**Comment by voracious** [comment]
Hey @gaminglifex. Thanks for raising this issue. Do you have a link to your project or another example project that I can use to reproduce this error?

**Comment by voracious** [comment]
@gaminglifex that works for me! As long as I can reproduce it, I should be able to get a fix together.

**Comment by voracious** [comment]
@gaminglifex thanks so much for the example! A [recent PR](https://github.com/voracious/vite-plugin-node-polyfills/pull/8) fixed a similar problem, and I verified it also fixed the error you encountered. If you update to `v0.5.0`, things should be working!

**Comment by gaminglifex** [comment]
Thank you!
